# Generated by Django 5.2 on 2025-05-26 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('canal_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('tipo_cliente', models.CharField(choices=[('mayorista', 'Mayorista'), ('cobertura', 'Cobertura'), ('mercado', 'Mercado'), ('institucional', 'Institucional'), ('todos', 'Todos')], default='todos', help_text='Clasificación del cliente para promociones.', max_length=20)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.canalcliente')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProveedor',
            fields=[
                ('grupo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_proveedor', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('linea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_producto', to='core.empresa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.grupoproveedor')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_ean', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(max_length=20)),
                ('unidad_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad_reparto', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad_bonificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('factor_reparto', models.IntegerField(blank=True, null=True)),
                ('factor_compra', models.IntegerField(blank=True, null=True)),
                ('factor_bonificacion', models.IntegerField(blank=True, null=True)),
                ('tipo_afectacion', models.CharField(max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('afecto_retencion', models.BooleanField(default=False)),
                ('afecto_detraccion', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='core.empresa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='core.grupoproveedor')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='core.linea')),
            ],
            options={
                'unique_together': {('empresa', 'codigo_articulo')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.canalcliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('bonificacion', 'Bonificación'), ('descuento', 'Descuento'), ('combinado', 'Combinado')], max_length=20)),
                ('aplica_por', models.CharField(choices=[('productos_condicion', 'Cantidad/Monto de Productos en Condición'), ('total_pedido', 'Monto Total del Pedido'), ('conjunto_obligatorio', 'Compra Conjunta de Productos Específicos')], max_length=30)),
                ('es_escalonada', models.BooleanField(default=False)),
                ('es_proporcional_directa', models.BooleanField(default=False, help_text='Si no es escalonada, ¿es proporcional?')),
                ('base_cantidad_proporcional_directa', models.IntegerField(blank=True, null=True)),
                ('base_monto_proporcional_directa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_cliente', models.CharField(choices=[('mayorista', 'Mayorista'), ('cobertura', 'Cobertura'), ('mercado', 'Mercado'), ('institucional', 'Institucional'), ('todos', 'Todos')], default='todos', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0, help_text='Menor número, mayor prioridad.')),
                ('canal_cliente_aplicable', models.ForeignKey(blank=True, help_text='Si vacío, aplica a todos los canales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='core.canalcliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaPromocion',
            fields=[
                ('escalapromocion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_escala', models.CharField(blank=True, max_length=100, null=True)),
                ('desde_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hasta_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desde_cantidad', models.IntegerField(blank=True, null=True)),
                ('hasta_cantidad', models.IntegerField(blank=True, null=True)),
                ('proporcional', models.BooleanField(default=False, help_text='¿Esta escala aplica beneficio proporcionalmente?')),
                ('base_cantidad_proporcional_escala', models.IntegerField(blank=True, null=True)),
                ('base_monto_proporcional_escala', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='core.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('detallepedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_linea', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_bonificacion', models.BooleanField(default=False, help_text='True si este item es bonificación y precio es 0.')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_pedidos', to='core.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
                ('promocion_origen', models.ForeignKey(blank=True, help_text='Promoción que originó este ítem si es bonificación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bonificados_generados', to='core.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionPromocion',
            fields=[
                ('condicionpromocion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_minima', models.IntegerField(blank=True, null=True)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('obligatoria_en_conjunto', models.BooleanField(default=False, help_text="Si promo es 'conjunto_obligatorio', este item es mandatorio.")),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_promocion', to='core.articulo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_promocion', to='core.grupoproveedor')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_promocion', to='core.linea')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='core.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioPromocion',
            fields=[
                ('beneficiopromocion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('bonificacion', 'Bonificación de Producto'), ('descuento', 'Descuento en Porcentaje')], max_length=20)),
                ('cantidad_bonificada', models.IntegerField(blank=True, null=True)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('articulo_bonificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_bonificacion_en', to='core.articulo')),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.escalapromocion')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_directos', to='core.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionAplicada',
            fields=[
                ('promocionaplicada_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_beneficios_obtenidos', models.TextField(blank=True, null=True)),
                ('monto_descuento_generado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('escala_aplicada', models.ForeignKey(blank=True, help_text='Escala específica que se activó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_en_pedidos', to='core.escalapromocion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_aplicadas', to='core.pedido')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_en_pedidos', to='core.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='promocion',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Si vacío, aplica a todas las sucursales de la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nro_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_identificacion_id', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('nro_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('territorio', models.CharField(blank=True, max_length=100, null=True)),
                ('rol_id', models.IntegerField(blank=True, null=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='core.canalcliente')),
            ],
        ),
    ]
