# Generated by Django 5.2 on 2025-05-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_ean', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(max_length=20)),
                ('unidad_compra', models.CharField(max_length=20)),
                ('unidad_reparto', models.CharField(max_length=20)),
                ('unidad_bonificacion', models.CharField(max_length=20)),
                ('factor_reparto', models.IntegerField()),
                ('factor_compra', models.IntegerField()),
                ('factor_bonificacion', models.IntegerField()),
                ('tipo_afectacion', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('afecto_retencion', models.BooleanField()),
                ('afecto_detraccion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bonificacion', 'Bonificación'), ('descuento', 'Descuento')], max_length=20)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('nro_documento', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.canalcliente')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.CreateModel(
            name='GrupoProveedor',
            fields=[
                ('grupo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupoproveedor'),
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('linea_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupoproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.IntegerField(blank=True, null=True)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_maxima', models.IntegerField(blank=True, null=True)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('obligatoria', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.linea')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.linea'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canalcliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('bonificacion', 'Bonificación'), ('descuento', 'Descuento'), ('combinado', 'Combinado')], max_length=20)),
                ('aplica_por', models.CharField(choices=[('monto', 'Monto Total'), ('cantidad', 'Cantidad Total'), ('monto_producto', 'Monto Producto'), ('cantidad_producto', 'Cantidad Producto'), ('mixto', 'Mixto')], max_length=30)),
                ('es_escalonada', models.BooleanField(default=False)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canalcliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hasta_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desde_cantidad', models.IntegerField(blank=True, null=True)),
                ('hasta_cantidad', models.IntegerField(blank=True, null=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiopromocion')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condicionpromocion')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocion')),
            ],
        ),
        migrations.AddField(
            model_name='condicionpromocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocion'),
        ),
        migrations.AddField(
            model_name='beneficiopromocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocion'),
        ),
        migrations.CreateModel(
            name='PromocionAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bonificado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='promocion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nro_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_identificacion_id', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('nro_movil', models.CharField(max_length=20)),
                ('supervisor', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('territorio', models.CharField(max_length=100)),
                ('rol_id', models.IntegerField()),
                ('canal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.canalcliente')),
            ],
        ),
    ]
