# Generated by Django 5.2 on 2025-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta unitario del artículo. Puede ser nulo y especificarse en el pedido.', max_digits=10, null=True),
        ),
    ]
